---
- name: INITIALIZE KUBE
  hosts: kube-cluster
  become: True

  tasks:
    - name: CHECK CPU CORE
      shell: nproc --all
      register: cpu_total
      failed_when: cpu_total.rc <= 1

    - name: PULL KUBE IMAGES
      shell: kubeadm config images pull

    - name: INITIALIZE KUBE
      shell: kubeadm init >> kube_init.log
      args:
        chdir: $HOME
        creates: kube_init.log
      tags: kube_init

    - name: CREATE .KUBE DIR
      file:
        path: $HOME/.kube
        state: directory
        mode: 0755

    - name: COPY ADMIN.CONF TO KUBE HOMEDIR
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/centos/.kube/config
        remote_src: yes

    - name: CREATE POD NETWORK
      shell: kubectl apply -f "https://cloud.weave.works/k8s/net?k8s-version=$(kubectl version | base64 | tr -d '\n')" >>  kube_pod.log
      args:
        chdir: $HOME
        creates: kube_pod.log
      tags: kube_pod

- hosts: kube-master
  gather_facts: false
  tasks:
        - name: GET KUEBADM JOIN
          shell: grep -A1 "kubeadm join" kube_init.log
          register: kube_join_raw

        - name: set join command
          set_fact:
            kube_join: "{{ kube_join_raw.stdout_lines[0] }}"


- hosts: kube-workers
  tasks:
        - name: JOIN CLUSTER
          shell: "{{ hostvars['kube-master'].kube_join }}  >> kubeadm_join.log"
          args:
            chdir: $HOME
            creates: kubeadm_join.log

